### ISSUE TITLE
PolygonPatch with attribute 'srsName'

### ISSUE THREAD

**Issue by DoraKar** [inspire-eu-validation/data-su#7]
Hi,

Our response includes statistical grid cell with PolygonPatch geometry that has EPSG code. While validating the response, validator throws an error: 
`cvc-complex-type.3.2.2: Attribute 'srsName' is not allowed to appear in element 'gml:PolygonPatch'`
Attribute 'srsName' is allowed by INSPIRE specification, but still validator throws an error. By removing the attribute, all tests pass. 
Is there an option of generating the response that will containt srsName and will pass INSPIRE validator tests or is there a bug in validator?

Thank you for your response.

Kind regards,
Dora & Dario

**Comment by MarcoMinghini** [comment]
Dear @DoraKar,
please note that this issue tracker is not actively monitored. The official INSPIRE Reference Validator helpdesk is available as the issue tracker of [this repository](https://github.com/INSPIRE-MIF/helpdesk-validator), so I invite you to open the issue there.

Kind regards,
Marco
